[package]
name = "xtp-sys"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
cc = "1.0.58"
fs_extra = "1.1.0"
bindgen = { version = "0.57.0", optional = true }
cfg-if = "*"

[features]
xtpbind = ["bindgen"]
