[package]
name = "abyss-macros"
version = "0.1.0"
authors = ["徐敏辉 <xuminhui_jia@126.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0.7"
proc-macro2 = "1.0"
darling = "0.20"
heck = "*"
